{{ if .Values.database.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-firstvoices-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.inClusterConfiguration.pvc.size }}
  {{ end }}
