{{ if .Values.database.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-firstvoices-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.database.inClusterConfiguration.username }}
  password: {{ .Values.database.inClusterConfiguration.password }}
{{ end }}
