apiVersion: v1
kind: Service
metadata:
  name: frontend-v1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend-v1
  ports:
    - name: http
      port: 3001
      targetPort: 3001
