{{ if .Values.database.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-firstvoices
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      name: postgresql-firstvoices
      labels:
        app: postgresql-firstvoices
    spec:
      serviceAccountName: gke-sql-sk2
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgresql-firstvoices-pv-claim
        - name: backups
          persistentVolumeClaim:
            claimName: db-snapshot-holder
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - {{ .Values.firstvoices.databaseGCloudSidecarParameters }}
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "1Gi"
              cpu:    "1"
        - name: postgresql-firstvoices
          image: postgres:13-alpine
          resources:
            requests:
              cpu: 1
              memory: "2000M"
            limits:
              cpu: 2
              memory: "2000M"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-firstvoices-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-firstvoices-credentials
                  key: password
            - name: POSTGRES_DB
              value: 'fv'
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pgdata
              subPath: data
            - mountPath: "/mnt/backups"
              name: backups
  selector:
    matchLabels:
      app: postgresql-firstvoices
  {{ end }}
