{{ if .Values.smtplogger.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: smtplogger
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: smtplogger
  ports:
    - port: 2500
      targetPort: 2500
{{ end }}
