version: '3'
services:
  cypress:
    image: "me/cypress"
    container_name: cypress
    command: "--browser chrome --record false --headless"
    volumes:
      - '../frontend/cypress/videos:/cypress/videos'
      - '../frontend/cypress/screenshots:/cypress/screenshots'
    depends_on:
      - frontend
      - nuxeo
      - elasticsearch
    environment:
      - WAIT_HOSTS=frontend:80, nuxeo:8080, elasticsearch:9200
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_AFTER_HOSTS=15
      - WAIT_HOSTS_TIMEOUT=120
      - CYPRESS_FV_USERNAME
      - CYPRESS_FV_PASSWORD
      - CYPRESS_PROJECT_ID
      - CYPRESS_RECORD_KEY