version: '3'
services:
  nuxeo-backend:
    image: me/nuxeo-dev
    container_name: nuxeo-dev
    volumes:
      - '${PWD}/fixtures:/opt/fixtures'
      - '${PWD}/nuxeo_dev_docker:/opt/nuxeo/server/nxserver/tmp'
      - '${PWD}/nuxeo_dev_docker/data:/opt/nuxeo/ext_data'
      - '${PWD}/nuxeo_dev_docker/logs:/var/log/nuxeo'
    ports:
      - '8080:8080'
      - '8787:8787'
    environment:
      - NUXEO_PACKAGES=nuxeo-dam nuxeo-jsf-ui
      - NUXEO_AUTOMATION_TRACE=false
      - NUXEO_DEV_MODE=false
      - NUXEO_DATA=/opt/nuxeo/ext_data
      - NUXEO_CLID=CLID
      - NUXEO_URL=http://localhost:8080/nuxeo
      - CYPRESS_FV_USERNAME
      - CYPRESS_FV_PASSWORD
    labels:
      - "ca.firstvoices.group=local_docker"
  frontend:
    image: me/fv-web-ui
    container_name: fv-web-ui
    ports:
      - '3001:80'
      - '3002:81'
    environment:
      WAIT_HOSTS: nuxeo-backend:8080
      WAIT_SLEEP_INTERVAL: 15
      WAIT_AFTER_HOSTS: 15
      WAIT_HOSTS_TIMEOUT: 120
    depends_on:
      - nuxeo-backend
    labels:
      - "ca.firstvoices.group=local_docker"