version: '3'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.4'
    container_name: nuxeo-elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
      - '443:443'
    environment:
      - discovery.type=single-node
      - cluster.name=firstvoices
  nuxeo:
    image: me/nuxeo-dev
    container_name: nuxeo-dev
    volumes:
      - '${PWD}/nuxeo_dev_docker:/opt/nuxeo/server/nxserver/tmp'
      - '${PWD}/nuxeo_dev_docker/data:/opt/nuxeo/ext_data'
      - '${PWD}/nuxeo_dev_docker/logs:/var/log/nuxeo'
    ports:
      - '8080:8080'
      - '8787:8787'
    environment:
      - NUXEO_PACKAGES=nuxeo-dam nuxeo-jsf-ui
      - NUXEO_AUTOMATION_TRACE=false
      - NUXEO_DEV_MODE=false
      - NUXEO_DATA=/opt/nuxeo/ext_data
      - NUXEO_CLID=CLID
      - 'NUXEO_URL=http://localhost:8080/nuxeo'
      - CYPRESS_FV_USERNAME
      - CYPRESS_FV_PASSWORD
    depends_on:
      - elasticsearch

  frontend:
    image: me/fv-web-ui
    container_name: fv-web-ui
    ports:
      - '80:80'
    depends_on:
      - nuxeo
