version: '3'
services:
  frontend:
    image: me/fv-web-ui
    container_name: fv-web-ui
    ports:
      - '3001:80'
    environment:
      WAIT_HOSTS: nuxeo:8080, elasticsearch:9200
      WAIT_SLEEP_INTERVAL: 15
      WAIT_AFTER_HOSTS: 15
      WAIT_HOSTS_TIMEOUT: 120
    depends_on:
      - nuxeo