domainSuffix: .local
hostSuffix: ""
namespace: default

frontendV1:
  image: frontend-v1:latest
frontendV2:
  image: frontend-v2:latest
firstvoices:
  image: firstvoices-skaffold:latest
  javaDebug: true
database_restoration:
  deploy: false
  image: database_restoration:latest
smtplogger:
  deploy: true
  image: smtplogger:latest

elastic:
  deploy: false
  useExternal: false
  inClusterConfiguration:
    pvc:
      size: "25Gi"
  externalConfiguration:
    url: "http://some-elastic-server:80"
    clusterName: elastic
    indexName: nuxeo

database:
  deploy: false
  useExternal: false
  inClusterConfiguration:
    pvc:
      size: "40Gi"
    name: fv
    username: fv_ra
    password: devdevdev
  externalConfiguration:
    host: "some-postgres-server"
    port: 5432
    name: fv
    username: "sa"
    password: "sa"

smtp:
  useExternal: false
  mailFrom: "nuxeo@test"
  externalConfiguration:
    host: somewhere
    port: 587

ingress:
  class: public
  certManagerTLS: true


# XS S M L XL XXL supported
resourceSizing: M

storageClassName: default

