name: Build

on:
  # Every day at 2:30am pst
  schedule:
    # cron: '30 9 * * *'
    - cron: '0 0 * * *'
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Copy settings.xml 
      run: cp sample.settings.xml ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn clean install
