name: Build

on:
  # Every day at 9:30 UTC
  #   schedule:
  #     - cron: '30 9 * * *'
#  push:
#    branches:
#      - master
  pull_request:
    branches:
      - master

jobs:

  build_linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@master
        id: changed-frontend
        with:
          paths: frontend/*/ frontend/index.html

      - uses: marceloprado/has-changed-path@master
        id: changed-package
        with:
          paths: frontend/package.json frontend/package-lock.json package-lock.json

      - uses: marceloprado/has-changed-path@master
        id: changed-backend
        with:
          paths: FirstVoices* FV* pom.xml

      - name: Set up JDK 1.8
        if: steps.changed-backend.outputs.changed == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js for use with actions
        if: steps.changed-backend.outputs.changed == 'true' || steps.changed-frontend.outputs.changed == 'true' || steps.changed-package.outputs.changed == 'true'
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '8.x'

      - name: Build only backend with Maven
        if: steps.changed-backend.outputs.changed == 'true' && steps.changed-frontend.outputs.changed == 'false'
        run: mvn clean install -p dev

      - name: Build frontend
        if: steps.changed-backend.outputs.changed == 'false' && steps.changed-frontend.outputs.changed == 'true'
        run: npm run build:production

      - name: Build entire project with Maven
        if: steps.changed-backend.outputs.changed == 'true' && steps.changed-frontend.outputs.changed == 'true'
        run: mvn clean install

      - name: Install Node packages
        if: steps.changed-package.outputs.changed == 'true' && steps.changed-backend.outputs.changed == 'false' && steps.changed-frontend.outputs.changed == 'false'
        run: |
          cd frontend
          npm install

#   build_mac:

#     runs-on: macos-latest

#     steps:

#       - uses: actions/checkout@v1
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Build with Maven
#         run: mvn clean install

#   build_windows:

#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Build with Maven
#         run: mvn clean install


