name: Cypress Tests

on: 
  pull_request:
    branches: 
      - master

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '8.x'

      - name: Build project and setup directories
        run: |
          cd docker
          bash ./setup_docker.sh

      - name: Startup backend
        run: |
          docker run --name nuxeo-dev -t --rm -p 8080:8080 -v ${PWD}/docker/nuxeo_dev_docker:/opt/nuxeo/server/nxserver/tmp -v ${PWD}/docker/nuxeo_dev_docker/data:/opt/nuxeo/ext_data -v ${PWD}/docker/nuxeo_dev_docker/logs:/var/log/nuxeo -e NUXEO_PACKAGES="nuxeo-dam " -e CYPRESS_FV_USERNAME -e CYPRESS_FV_PASSWORD -d me/nuxeo-dev
          sleep 120
        env:
          CYPRESS_FV_USERNAME: ${{ secrets.CYPRESS_FV_USERNAME }}
          CYPRESS_FV_PASSWORD: ${{ secrets.CYPRESS_FV_PASSWORD }}

      - name: Initial backend setup
        env:
          CYPRESS_FV_USERNAME: ${{ secrets.CYPRESS_FV_USERNAME }}
          CYPRESS_FV_PASSWORD: ${{ secrets.CYPRESS_FV_PASSWORD }}
        run: |
          bash ./docker/initialsetup.sh

      - name: Run Cypress tests
        env:
          CYPRESS_FV_USERNAME: ${{ secrets.CYPRESS_FV_USERNAME }}
          CYPRESS_FV_PASSWORD: ${{ secrets.CYPRESS_FV_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        run: |
          cd frontend
          npm run test:e2e:ci
          echo "Testing Completed"