name: Cypress Tests

on: 
  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '8.x'
    
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
    
#     - name: Run Cypress tests
#       run: npm run test:e2e:dev:headless
