on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
#      Code is built with Maven: run 'org.sonarsource.scanner.maven:sonar' during the build.
#      Otherwise, we would be able to use this. TODO: LOOK AT DOING THIS WITH FRONTEND
#      - uses: actions/checkout@v2
#        with:
#          # Disabling shallow clone is recommended for improving relevancy of reporting
#          fetch-depth: 0
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Run Sonar Coverage on Backend
      run: mvn sonar:sonar -Dsonar.branc.name=${BRANCH_NAME} -Dsonar.login=${{ secrets
      .SONAR_LOGIN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=first-peoples-cultural-council





