apiVersion: skaffold/v2beta13
kind: Config
profiles:
  - name: kaniko-build
    activation:
      - env: BUILD_MODE=kaniko
  - name: docker-build
    activation:
      - env: BUILD_MODE=docker
  - name: use-m2-build-cache
    activation:
      - env: USE_M2_BUILD_CACHE=true
  - name: kaniko-apply-dockerconfig
    activation:
      - env: USE_KANIKO_DOCKER_SECRET=true
  - name: use-kaniko-namespace
    activation:
      - env: USE_KANIKO_NAMESPACE=true
  - name: use-kaniko-node-selector
    activation:
      - env: USE_KANIKO_NODE_SELECTOR=true
requires:
  - path: skaffold.build.docker.yaml

  - path: skaffold.build.kaniko.yaml
    activeProfiles:
      - name: kaniko-build
        activatedBy: [ kaniko-build ]
      - name: m2-cached
        activatedBy: [ use-m2-build-cache ]
      - name: kaniko-apply-dockerconfig
        activatedBy: [ kaniko-apply-dockerconfig ]
      - name: kaniko-use-namespace
        activatedBy: [ use-kaniko-namespace ]
      - name: kaniko-use-node-selector
        activatedBy: [ use-kaniko-node-selector]
  - path: skaffold.deploy.yaml
