apiVersion: skaffold/v1beta17
kind: Config
build:
  artifacts:
  - image: envoy
    context: dockerfiles/envoy
  - image: firstvoices
    context: dockerfiles/firstvoices
  local:
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - k8s/k8s-*
